services:
  - type: web
    name: nubian-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: nubian_landing
      - key: CORS_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
